[config]
skip_core_tasks = true
skip_crate_env_info = true
skip_git_env_info = true
skip_rust_env_info = false

[tasks."dev"]
command = "cargo-tauri"
args = [ "dev" ]

[tasks."check"]
watch.watch = [ "./src-tauri" ]
script = "cargo clippy"
cwd = "src-tauri"

[tasks.build]
command = "cargo-tauri"
args = [ "build", "--target", "x86_64-pc-windows-msvc" ]
