[config]
skip_core_tasks = true
skip_crate_env_info = true
skip_git_env_info = true
skip_rust_env_info = false

[tasks."dev"]
script = "npx tauri dev"

[tasks.build]
windows.script = "npx tauri build --target x86_64-pc-windows-msvc"
