name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions-rust-lang/setup-rust-toolchain@v1.11.0
        name: Setup Cache
      - name: Build
        run: cargo build --verbose
      - name: Copy manifest
        run: cp .\cefbased.exe.manifest .\target\debug\
      - uses: actions/upload-artifact@v4.6.2
        name: Upload build
        with:
          name: win.exe
          path: target/debug/samurai-browser.exe
          overwrite: true
